### PR TITLE
fix: [Orchestration] duplicated properties

### LINKED ISSUE #474: Additional system prompt gets added when using TemplateConfig.create() with ai-sdk-core v1.8.0
### Describe the Bug

Code works with v1.6.0 of ai-sdk-core but when upgraded to v1.8.0, an additional system prompt is getting added to the LLM request which causes a failure if there's a system prompt already in place.

### Steps to Reproduce

1. Use AI SDK version 1.8.0
2. Create a template config with a system prompt and a user prompt
3. Send the prompt to the LLM using the `client.chatCompletion(...)` method

### Expected Behavior

Only the system prompt mentioned in the code should be sent to the LLM

### Screenshots

_No response_

### Used Versions

- Java and Maven version via `mvn --version`: ...
- SAP Cloud SDK for AI version: ...
- Spring Boot or CAP version: ...
- <details><summary>Dependency tree via `mvn dependency:tree`</summary>
    
    ```
    [INFO] ---------------< com.sap.it.ai.service:script-optimizer >---------------
  [INFO] Building script-optimizer 1.0.0-SNAPSHOT                           [3/5]
  [INFO]   from script-optimizer/pom.xml
  [INFO] --------------------------------[ jar ]---------------------------------
  [INFO] 
  [INFO] --- dependency:3.7.0:tree (default-cli) @ script-optimizer ---
  [INFO] com.sap.it.ai.service:script-optimizer:jar:1.0.0-SNAPSHOT
  [INFO] +- com.sap.it.ai.service:common-modules:jar:1.0.0-SNAPSHOT:compile
  [INFO] +- org.apache.groovy:groovy:jar:4.0.26:compile
  [INFO] +- org.springframework.boot:spring-boot:jar:3.4.3:compile
  [INFO] +- org.springframework:spring-context:jar:6.2.1:compile
  [INFO] |  +- org.springframework:spring-aop:jar:6.2.1:compile
  [INFO] |  +- org.springframework:spring-expression:jar:6.2.1:compile
  [INFO] |  \- io.micrometer:micrometer-observation:jar:1.14.2:compile
  [INFO] |     \- io.micrometer:micrometer-commons:jar:1.14.2:compile
  [INFO] +- org.springframework:spring-core:jar:6.2.1:compile
  [INFO] |  \- org.springframework:spring-jcl:jar:6.2.1:compile
  [INFO] +- org.springframework:spring-web:jar:6.2.1:compile
  [INFO] +- org.springframework:spring-webmvc:jar:6.2.1:compile
  [INFO] +- org.springframework:spring-beans:jar:6.2.1:compile
  [INFO] +- org.springframework.boot:spring-boot-starter-oauth2-resource-server:jar:3.4.3:compile
  [INFO] |  +- org.springframework.boot:spring-boot-starter:jar:3.4.3:compile
  [INFO] |  |  \- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
  [INFO] |  +- org.springframework.security:spring-security-config:jar:6.4.3:compile
  [INFO] |  +- org.springframework.security:spring-security-core:jar:6.4.3:compile
  [INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:6.4.3:compile
  [INFO] |  +- org.springframework.security:spring-security-oauth2-resource-server:jar:6.4.3:compile
  [INFO] |  |  \- org.springframework.security:spring-security-oauth2-core:jar:6.4.3:compile
  [INFO] |  \- org.springframework.security:spring-security-oauth2-jose:jar:6.4.3:compile
  [INFO] +- org.springframework.boot:spring-boot-starter-oauth2-authorization-server:jar:3.4.3:compile
  [INFO] |  \- org.springframework.security:spring-security-oauth2-authorization-server:jar:1.4.2:compile
  [INFO] +- org.springframework.boot:spring-boot-starter-oauth2-client:jar:3.4.3:compile
  [INFO] |  \- org.springframework.security:spring-security-oauth2-client:jar:6.4.3:compile
  [INFO] |     \- com.nimbusds:oauth2-oidc-sdk:jar:9.43.6:compile
  [INFO] |        +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
  [INFO] |        +- com.nimbusds:content-type:jar:2.2:compile
  [INFO] |        \- com.nimbusds:lang-tag:jar:1.7:compile
  [INFO] +- org.springframework.boot:spring-boot-starter-logging:jar:3.4.3:compile
  [INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.24.3:compile
  [INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.24.3:compile
  [INFO] |  \- org.slf4j:jul-to-slf4j:jar:2.0.16:compile
  [INFO] +- org.springframework.boot:spring-boot-starter-security:jar:3.4.3:compile
  [INFO] |  \- org.springframework.security:spring-security-web:jar:6.4.3:compile
  [INFO] +- com.sap.cloud.security:java-security:jar:3.5.8:compile
  [INFO] |  +- com.sap.cloud.security:java-api:jar:3.5.7:compile
  [INFO] |  +- com.sap.cloud.security:env:jar:3.5.7:compile
  [INFO] |  |  +- com.sap.cloud.environment.servicebinding:java-sap-vcap-services:jar:0.20.0:compile
  [INFO] |  |  +- com.sap.cloud.environment.servicebinding:java-sap-service-operator:jar:0.20.0:compile
  [INFO] |  |  +- com.sap.cloud.environment.servicebinding.api:java-consumption-api:jar:0.20.0:compile
  [INFO] |  |  \- org.json:json:jar:20250107:compile
  [INFO] |  +- commons-io:commons-io:jar:2.18.0:compile
  [INFO] |  \- com.sap.cloud.security.xsuaa:token-client:jar:3.5.7:compile
  [INFO] +- com.sap.cloud.security.xsuaa:spring-xsuaa:jar:3.5.8:compile
  [INFO] |  +- com.nimbusds:nimbus-jose-jwt:jar:10.0.1:compile
  [INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
  [INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
  [INFO] |  |  \- commons-codec:commons-codec:jar:1.11:compile
  [INFO] |  \- com.github.ben-manes.caffeine:caffeine:jar:3.2.0:compile
  [INFO] |     +- org.jspecify:jspecify:jar:1.0.0:compile
  [INFO] |     \- com.google.errorprone:error_prone_annotations:jar:2.36.0:compile
  [INFO] +- org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j:jar:3.2.1:compile
  [INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:4.2.1:compile
  [INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:4.2.1:compile
  [INFO] |  |  \- org.springframework.cloud:spring-cloud-commons:jar:4.2.1:compile
  [INFO] |  +- org.springframework.cloud:spring-cloud-circuitbreaker-resilience4j:jar:3.2.1:compile
  [INFO] |  |  +- io.github.resilience4j:resilience4j-spring-boot3:jar:2.2.0:compile
  [INFO] |  |  |  \- io.github.resilience4j:resilience4j-spring6:jar:2.2.0:compile
  [INFO] |  |  |     +- io.github.resilience4j:resilience4j-annotations:jar:2.2.0:compile
  [INFO] |  |  |     +- io.github.resilience4j:resilience4j-consumer:jar:2.2.0:compile
  [INFO] |  |  |     |  \- io.github.resilience4j:resilience4j-circularbuffer:jar:2.2.0:runtime
  [INFO] |  |  |     \- io.github.resilience4j:resilience4j-framework-common:jar:2.2.0:compile
  [INFO] |  |  \- org.springframework.boot:spring-boot-configuration-processor:jar:3.4.3:annotationProcessor
  [INFO] |  +- io.github.resilience4j:resilience4j-circuitbreaker:jar:2.3.0:compile
  [INFO] |  |  \- io.github.resilience4j:resilience4j-core:jar:2.3.0:compile
  [INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.0:compile
  [INFO] |  |        +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.0:compile
  [INFO] |  |        |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.0:compile
  [INFO] |  |        |  \- org.jetbrains:annotations:jar:13.0:compile
  [INFO] |  |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.0:compile
  [INFO] |  +- io.github.resilience4j:resilience4j-timelimiter:jar:2.3.0:compile
  [INFO] |  \- io.github.resilience4j:resilience4j-reactor:jar:2.2.0:compile
  [INFO] |     +- io.github.resilience4j:resilience4j-ratelimiter:jar:2.3.0:compile
  [INFO] |     +- io.github.resilience4j:resilience4j-bulkhead:jar:2.3.0:runtime
  [INFO] |     +- io.github.resilience4j:resilience4j-retry:jar:2.3.0:compile
  [INFO] |     \- io.github.resilience4j:resilience4j-micrometer:jar:2.2.0:compile
  [INFO] +- org.springframework.boot:spring-boot-starter-aop:jar:3.4.3:compile
  [INFO] |  \- org.aspectj:aspectjweaver:jar:1.9.22.1:compile
  [INFO] +- com.sap.ai.sdk:core:jar:1.8.0:compile
  [INFO] |  +- com.sap.cloud.sdk.cloudplatform:connectivity-apache-httpclient5:jar:5.16.0:compile
  [INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:caching:jar:5.16.0:compile
  [INFO] |  |  \- com.sap.cloud.sdk.cloudplatform:tenant:jar:5.16.0:compile
  [INFO] |  +- com.sap.cloud.environment.servicebinding.api:java-access-api:jar:0.20.0:compile
  [INFO] |  +- com.sap.cloud.environment.servicebinding.api:java-core-api:jar:0.20.0:compile
  [INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.4.1:compile
  [INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.3.1:compile
  [INFO] |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.3.2:compile
  [INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.18.2:compile
  [INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.18.2:compile
  [INFO] |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.18.2:compile
  [INFO] |  +- com.google.guava:guava:jar:33.4.0-jre:compile
  [INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.2:compile
  [INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
  [INFO] |  |  +- org.checkerframework:checker-qual:jar:3.48.4:compile
  [INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:3.0.0:compile
  [INFO] |  +- org.slf4j:slf4j-api:jar:2.0.16:compile
  [INFO] |  +- io.vavr:vavr:jar:0.10.5:compile
  [INFO] |  |  \- io.vavr:vavr-match:jar:0.10.5:compile
  [INFO] |  +- io.github.cdimascio:dotenv-java:jar:3.1.0:compile
  [INFO] |  \- com.sap.cloud.sdk.cloudplatform:connectivity-oauth:jar:5.16.0:runtime
  [INFO] |     +- com.sap.cloud.sdk.cloudplatform:connectivity-apache-httpclient4:jar:5.16.0:runtime
  [INFO] |     \- com.sap.cloud.sdk.cloudplatform:resilience:jar:5.16.0:runtime
  [INFO] |        \- com.sap.cloud.sdk.cloudplatform:resilience4j:jar:5.16.0:runtime
  [INFO] |           \- javax.cache:cache-api:jar:1.1.1:runtime
  [INFO] +- com.sap.ai.sdk:orchestration:jar:1.8.0:compile
  [INFO] |  +- com.github.victools:jsonschema-generator:jar:4.38.0:compile
  [INFO] |  |  \- com.fasterxml:classmate:jar:1.7.0:compile
  [INFO] |  +- com.github.victools:jsonschema-module-jackson:jar:4.38.0:compile
  [INFO] |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.19.0:compile
  [INFO] +- com.sap.ai.sdk.foundationmodels:openai:jar:1.8.0:compile
  [INFO] +- com.sap.ai.sdk:document-grounding:jar:1.8.0:compile
  [INFO] +- com.sap.cloud.sdk.cloudplatform:cloudplatform-core:jar:5.16.0:compile
  [INFO] +- com.sap.cloud.sdk.datamodel:openapi-core:jar:5.16.0:compile
  [INFO] +- org.springframework.ai:spring-ai-core:jar:1.0.0-M6:compile
  [INFO] |  +- com.fasterxml.jackson.module:jackson-module-jsonSchema:jar:2.18.2:compile
  [INFO] |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
  [INFO] |  +- io.swagger.core.v3:swagger-annotations:jar:2.2.25:compile
  [INFO] |  +- com.github.victools:jsonschema-module-swagger-2:jar:4.37.0:compile
  [INFO] |  +- org.antlr:ST4:jar:4.3.4:compile
  [INFO] |  |  \- org.antlr:antlr-runtime:jar:3.5.3:compile
  [INFO] |  +- org.antlr:antlr4-runtime:jar:4.13.1:compile
  [INFO] |  +- org.springframework:spring-messaging:jar:6.2.2:compile
  [INFO] |  +- io.micrometer:micrometer-core:jar:1.14.2:compile
  [INFO] |  |  +- org.hdrhistogram:HdrHistogram:jar:2.2.2:runtime
  [INFO] |  |  \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
  [INFO] |  +- io.micrometer:context-propagation:jar:1.1.2:compile
  [INFO] |  \- com.knuddels:jtokkit:jar:1.1.0:compile
  [INFO] +- org.springframework.boot:spring-boot-autoconfigure:jar:3.4.3:compile
  [INFO] +- io.projectreactor:reactor-core:jar:3.6.12:compile
  [INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
  [INFO] +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
  [INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.18.2:compile
  [INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.18.2:compile
  [INFO] +- org.yaml:snakeyaml:jar:2.0:compile
  [INFO] +- ch.qos.logback:logback-classic:jar:1.5.16:runtime
  [INFO] |  \- ch.qos.logback:logback-core:jar:1.5.16:runtime
  [INFO] +- com.sap.hcp.cf.logging:cf-java-logging-support-logback:jar:3.8.4:runtime
  [INFO] |  \- com.sap.hcp.cf.logging:cf-java-logging-support-core:jar:3.8.4:runtime
  [INFO] |     \- com.fasterxml.jackson.jr:jackson-jr-objects:jar:2.14.2:runtime
  [INFO] +- org.springframework.boot:spring-boot-starter-web:jar:3.4.3:runtime
  [INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:3.4.3:runtime
  [INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.18.2:runtime
  [INFO] |  \- org.springframework.boot:spring-boot-starter-tomcat:jar:3.4.3:runtime
  [INFO] |     +- org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.36:runtime
  [INFO] |     +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.36:runtime
  [INFO] |     \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:10.1.36:runtime
  [INFO] +- org.projectlombok:lombok:jar:1.18.36:provided
  [INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.11.4:test
  [INFO] |  +- org.opentest4j:opentest4j:jar:1.3.0:test
  [INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.11.4:test
  [INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
  [INFO] +- org.assertj:assertj-core:jar:3.27.3:test
  [INFO] |  \- net.bytebuddy:byte-buddy:jar:1.15.11:test
  [INFO] +- com.sap.cloud.sdk.cloudplatform:cloudplatform-connectivity:jar:5.16.0:compile
  [INFO] |  +- com.sap.cloud.sdk.cloudplatform:resilience-api:jar:5.16.0:compile
  [INFO] |  +- com.sap.cloud.sdk.cloudplatform:security:jar:5.16.0:compile
  [INFO] |  +- org.slf4j:jcl-over-slf4j:jar:2.0.16:runtime
  [INFO] |  +- com.mikesamuel:json-sanitizer:jar:1.2.3:compile
  [INFO] |  +- org.apache.commons:commons-lang3:jar:3.17.0:compile
  [INFO] |  +- com.auth0:java-jwt:jar:4.4.0:compile
  [INFO] |  +- org.bouncycastle:bcprov-jdk18on:jar:1.80:compile
  [INFO] |  \- org.bouncycastle:bcpkix-jdk18on:jar:1.80:compile
  [INFO] |     \- org.bouncycastle:bcutil-jdk18on:jar:1.80:compile
  [INFO] +- org.slf4j:slf4j-simple:jar:2.0.16:test
  [INFO] +- org.springframework.boot:spring-boot-starter-test:jar:3.4.3:test
  [INFO] |  +- org.springframework.boot:spring-boot-test:jar:3.4.3:test
  [INFO] |  +- com.jayway.jsonpath:json-path:jar:2.9.0:test
  [INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.2:test
  [INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.3:test
  [INFO] |  +- net.minidev:json-smart:jar:2.5.2:compile
  [INFO] |  |  \- net.minidev:accessors-smart:jar:2.5.2:compile
  [INFO] |  |     \- org.ow2.asm:asm:jar:9.7.1:compile
  [INFO] |  +- org.awaitility:awaitility:jar:4.2.2:test
  [INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
  [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.11.4:test
  [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.11.4:test
  [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.11.4:test
  [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.11.4:test
  [INFO] |  +- org.mockito:mockito-core:jar:5.4.0:test
  [INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.14.5:test
  [INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
  [INFO] |  +- org.mockito:mockito-junit-jupiter:jar:5.14.2:test
  [INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.3:test
  [INFO] |  +- org.springframework:spring-test:jar:6.2.3:test
  [INFO] |  \- org.xmlunit:xmlunit-core:jar:2.10.0:test
  [INFO] \- org.springframework.boot:spring-boot-test-autoconfigure:jar:3.4.3:test

    ```
  </details>

### Code Examples

```java
final var templateConfig = getOrchestrationTemplate(scriptContent, beanOutputConverter);

val prompt =
    new OrchestrationPrompt(
        Map.of("kba", knowledgeBaseArticleManager.getAllKbaContentString()));

OrchestrationChatResponse response = null;

response =
    client.chatCompletion(
        prompt,
        config
            .withTemplateConfig(templateConfig)
            .withMaskingConfig(ConfigurationConstants.maskingConfig)
            .withInputFiltering(getInputFilterConfig())
            .withOutputFiltering(getOutputFilterConfig()));

private static OrchestrationTemplate getOrchestrationTemplate(
      String scriptContent, BeanOutputConverter<ScriptOptimizerOutput> beanOutputConverter) {

    val systemPrompt =
        Message.system(
            PromptConstants.CONTEXT_INITIALISATION_INSTRUCTION
                + PromptConstants.REVIEW_CONSIDERATION_INSTRUCTION
                + PromptConstants.KBA_INSTRUCTION
                + PromptConstants.STOP_OPTIMIZATION_INSTRUCTION
                + PromptConstants.DELIMITER_INSTRUCTION
                + beanOutputConverter.getFormat());
    val userPrompt = Message.user(scriptContent);

    return TemplateConfig.create()
        .withTemplate(List.of(systemPrompt.createChatMessage(), userPrompt.createChatMessage()));
  }
```

### Stack Trace

org.apache.hc.client5.http.wire          : http-outgoing-1 >> "AI-Client-Type: AI SDK Java[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "AI-Resource-Group: scriptOptimizationTest[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "Accept-Encoding: gzip, x-gzip, deflate[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "Host: api.ai.internalprod.eu-central-1.aws.ml.hana.ondemand.com[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "Content-Length: 13282[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "Content-Type: application/json; charset=UTF-8[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "Connection: keep-alive[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "User-Agent: Apache-HttpClient/5.4.1 (Java/17.0.14)[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "[\r][\n]"
org.apache.hc.client5.http.wire          : http-outgoing-1 >> "{"orchestration_config":{"module_configurations":{"llm_module_config":{"model_name":"anthropic--claude-3.5-sonnet","model_params":{"max_tokens":4096},"model_version":"1"},"templating_module_config":{"template":[{"role":"system","role":"system","content":[{"type":"text","text":" ..

Request failed with status 400 Bad Request and error message: '400 - LLM Module: Anthropic supports only one system message, and it must be provided as a single string.'

### Log File

<details><summary>Log file</summary>
...
</details>

### Affected Development Phase

Release

### Impact

Impaired

### Timeline

_No response_

### PR DESCRIPTION
**Pull request by CharlesDuboisSAP**
## Context

AI/ai-sdk-java-backlog#278.
Fixes #474 

Fixed duplicate properties, Anthropic Claude chat completions are now working.
⚠️This is only manually e2e tested since verify does not check for duplicate **equal** `key:values`

### Feature scope:
 
- [x] No duplicate keys on serialization
- [x] Tested with Claude 3.7

## Definition of Done

- [x] Functionality scope stated & covered
- [ ] Tests cover the scope above
- [ ] Error handling created / updated & covered by the tests above
- [ ] ~Aligned changes with the JavaScript SDK~
- [ ] [Documentation](https://github.com/SAP/ai-sdk/tree/main/docs-java) updated
- [ ] Release notes updated

### CODE REVIEW

File: orchestration/src/main/java/com/sap/ai/sdk/orchestration/JacksonMixins.java [hunk 1]
```diff
@@ -20,12 +21,9 @@ interface LLMModuleResultMixIn {}
   @JsonDeserialize(as = LLMChoice.class)
   interface ModuleResultsOutputUnmaskingInnerMixIn {}
 
-  @JsonTypeInfo(use = JsonTypeInfo.Id.NONE)
-  interface NoneTypeInfoMixin {}
-
   @JsonTypeInfo(
       use = JsonTypeInfo.Id.NAME,
-      include = JsonTypeInfo.As.PROPERTY,
+      include = As.EXISTING_PROPERTY,
```
Comment (CharlesDuboisSAP) [inline orchestration/src/main/java/com/sap/ai/sdk/orchestration/JacksonMixins.java:26]: `PROPERTY` is what duplicates properties

File: sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java [hunk 2]
```diff
@@ -381,8 +381,7 @@ void testLocalPromptTemplate() throws IOException {
   @Test
   void testStreamingErrorHandlingTemplate() {
     val template = Message.user("Bad template: {{?language!@#$}}");
-    val templatingConfig =
-        TemplateConfig.create().withTemplate(List.of(template.createChatMessage()));
+    val templatingConfig = TemplateConfig.create().withMessages(template);
```
Comment (CharlesDuboisSAP) [inline sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java:384]: Drive-by update of deprecated code

File: docs/release_notes.md [hunk 3]
```diff
@@ -30,4 +30,4 @@
 
 ### 🐛 Fixed Issues
 
--
+- [Orchestration] Fixed duplicate properties, Anthropic Claude chat completions are now working.
```
Comment (rpanackal) [inline docs/release_notes.md:33]:
```suggestion
- [Orchestration] Resolved duplicate JSON property issue, enabling Anthropic Claude chat completions.
```

**Review by rpanackal — DISMISSED** [review]

**Review by rpanackal — COMMENTED** [review]
I am assuming there would be another PR that takes care of the unit test json equality check.
